name: 🐛 Bug Report
description: Report a bug or issue with the CSP generator
title: "[Bug] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Test with the latest version
        - Provide as much detail as possible

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - '@csp-kit/generator (core library)'
        - '@csp-kit/data (service definitions)'
        - '@csp-kit/cli (command line tool)'
        - 'Web interface'
        - 'Documentation'
        - 'Other'
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: A clear and concise description of what actually happened
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: If applicable, provide a minimal code example that demonstrates the issue
      render: javascript
      placeholder: |
        import { generateCSP } from '@csp-kit/generator';
        import { GoogleAnalytics } from '@csp-kit/data';
        
        const result = generateCSP({
          services: [GoogleAnalytics]
        });
        console.log(result.header);
    validations:
      required: false

  - type: textarea
    id: error-output
    attributes:
      label: Error Messages/Output
      description: If applicable, provide any error messages or unexpected output
      render: text
      placeholder: Paste error messages, console output, or unexpected results here
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: e.g., 2.0.0, latest
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running this?
      options:
        - Node.js
        - Browser
        - Deno
        - Bun
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js? (if applicable)
      placeholder: e.g., 18.0.0, 20.0.0
    validations:
      required: false

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What browser and version? (if applicable)
      placeholder: e.g., Chrome 120, Firefox 119, Safari 17
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS 14, Ubuntu 22.04
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any other information that might be helpful in diagnosing the issue
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tested with the latest version
          required: true
        - label: I have provided a minimal reproduction example (if applicable)
          required: false